### ISSUE TITLE
Problem with unref

### ISSUE THREAD

**Issue by green13** [tj/co#283] opened 2016-07-22 09:09 UTC
I have some code with co and unref. After call redis.info thread exit from co function.

Example:
```javascript
"use strict";

const co    = require("co");
const redis = require("redis");

const client = redis.createClient();
client.unref(); // PROBLEM!
client.on("error", function (err) {
    throw err;
});


function callRedis() {
    return new Promise((resolve, reject) => {
        client.info((err, reply) => {
            console.log('callback');
            if (err) {
                throw err;
            }

            resolve(reply);
        });
    });
}


co(function*() {
    console.log('before');
    let data = yield callRedis();
    console.log('after'); // NO PRINT
}).catch(function (err) {
    console.error(err);
});

console.log('exit');
```

Output:
```
before
end
```

co 4.6.0
redis 2.6.2
node v5.0.0

**Comment by tj** [comment] 2016-07-22 14:22
At a glance it looks like you're early unref is causing node to think there's no work left to do

**Comment by green13** [comment] 2016-07-22 14:34
I solved the problem by removing unref and thought that it may be interesting.

**Comment by freiit** [comment] 2016-07-22 15:13
I didn't look deep into the issue, but I think the problem is, that you "throw" inside a callback. 

Has nothing todo with "co".  Just the Promise is never fulfilled. 

\Christoph

**Comment by tj** [comment] 2016-07-22 15:21
cool cool! closing since it's just a node thing

**Closed by tj** 2016-07-22 15:21 UTC
